### ISSUE TITLE
Unnecessary express-js dependency

### ISSUE THREAD

**Issue by mlcdf** [yourikopecky/choo-boilerplate#1]
Hi Youri,

Express-js is listed as a dependency in both the README and the package.json, but it looks like it isn't used anywhere in your code. Am I missing something?

**Comment by yourikopecky** [comment]
Hi,

You need express in order to launch [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html).

**Comment by yourikopecky** [comment]
Express is now in devDependencies.

**Comment by mlcdf** [comment]
Got it, thanks!
